---
apiVersion: v1
offerings:
  - name: Retrieval_Augmented_Generation_Pattern
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 5fdd0045-30fc-4013-a8bc-6db9d5447a52
    variations:
      - name: quickstart # Quick start with sample application (Deploy on Code Engine)
        mark_ready: true
        install_type: fullstack
